### ISSUE TITLE
Problem folding an LCA database

### ISSUE THREAD

**Issue by MaximeAgez** [polca/unfold#1]
Hi @romainsacchi,
I've been trying to fold two databases that I created in Activity-browser and an error popped up. I joined screenshots below:
![image](https://user-images.githubusercontent.com/24285636/221971167-9e9f1838-47b9-43e8-8d92-372eb53378a3.png)
![image](https://user-images.githubusercontent.com/24285636/221971324-f2390c26-5ad2-4482-82b1-a75927ac9239.png)

**Comment by romainsacchi** [comment]
I think the databases you are trying to fold contain datasets which miss some mandatory fields (in this case, the field unit). I will add a check routine tomorrow, to warn the user of missing fields and print a list of the guilty datasets. I will let you know.

**Comment by romainsacchi** [comment]
I think I may have solved the issue.
Can you try to update to `v.1.0.3` (from pip, or the latest from conda) and let me know?

**Comment by romainsacchi** [comment]
Hmm, it seems it was not pushed on conda, only pip.

**Comment by romainsacchi** [comment]
OK, it is on conda now as well.

**Comment by MaximeAgez** [comment]
I updated to 1.0.3. Now I face another Error:

![image](https://user-images.githubusercontent.com/24285636/222557074-e194ec29-eb6d-437d-bb37-04f4f25388dd.png)
![image](https://user-images.githubusercontent.com/24285636/222557098-6c672a17-d5c2-4e29-ab0b-35a9fcf45d11.png)

Seems like it does not think that my database is linked to ecoinvent. But it is linked to ecoinvent.

I tried with other databases in other projects with other versions of ecoinvent and the same error pops up.

**Comment by romainsacchi** [comment]
Hi @MaximeAgez ,

right, I think this is the expected behavior. The purpose of the library is to create a "mask" of a database that contains proprietary data. For example, let's say I made a copy of ecoinvent and modified some markets and some processes throughout the database. I cannot share my modified ecoinvent database, since 95% of it is still original ecoinvent data (as I modified only a few processes). `unfold` would create a "mask" (in the form of a data package) of that modified ecoinvent database that I can freely share (since it only contains differences between my modified database and the "reference" ecoinvent database). The users would apply this mask to their local original ecoinvent database, to reproduce my modified ecoinvent database.

So, in your case, I suspect "Glencore - Horne" is a database that simply links to the reference database (ecoinvent?), it is not a "modified" version of the reference database, since `unfold` could not detect any datasets in common.

The typical use I can think of would be when creating prospective LCA databases, which are often just modified ecoinvent databases where electricity markets have been changed, etc. This would allow reproducing these prospective LCA databases without sharing the databases themselves, but only the difference with respect to the unmodified database.

Hence, for example, we have [here](https://github.com/polca/replicate/blob/main/README.md) a list of data packages which one can unfold to reproduce locally some scenario-based LCA databases.

Do you think it deserves a better explanation in the paper/github repo?

**Comment by MaximeAgez** [comment]
Actually I reread the paper and it makes sense now. I misunderstood the purpose of the software but it's clearly stated, I was probably not as focused as I should have been.

I successfully folded and unfolded two premise-generated ecoinvent databases. But there is something that seems strange to me. Before folding the two databases had respectively 35549 and 34575 activities (it's ecoinvent_image_SSP2-Base_2023 and ecoinvent_image_SSP2-RCP19_2023, using ecoinvent3.8 cut-off). 

![image](https://user-images.githubusercontent.com/24285636/222758094-8ce7a2a5-1ce6-4626-b67a-a7602cbe7045.png)

After unfolding them in another project, the 1st one has now 34575 activities:
![image](https://user-images.githubusercontent.com/24285636/222757954-35db3c34-dbac-41bc-91a5-ebf36c70ae63.png)

Is that an expected behaviour?

**Comment by romainsacchi** [comment]
It is indeed surprising. 
Do you think you could help by running something like:

````

bw.project.set_current("premise")
list_act_db1 = [(d["name"], d["reference product"], d["location"]) for d in bw.Database("ecoinvent_image_SSP2-Base_2030")]

bw.project.set_current("ecoinvent3.8")
list_act_db2 = [(d["name"], d["reference product"], d["location"]) for d in bw.Database("ecoinvent_image_SSP2-Base_2030")]

print([d for d in list_act_db2 if d not in list_act_db1])

````

**Comment by MaximeAgez** [comment]
![image](https://user-images.githubusercontent.com/24285636/222828917-f5ecd5e5-1415-43cb-838a-4083c6f703d2.png)

**Comment by romainsacchi** [comment]
Hi @MaximeAgez,
indeed, thanks for noticing that. These redundant datasets belong to other folded scenarios.
Although they are orphans and empty, having them there is not nice.
In a few minutes, v.1.0.4 should be released, preventing this.

**Comment by MaximeAgez** [comment]
Works for me now. Thanks!
